function kinematics_loops7Joints6Links06_Aug20_20_57 = importfile(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  KINEMATICS_LOOPS7JOINTS6LINKS06_AUG20_20_57 = IMPORTFILE(FILE) reads
%  data from the first worksheet in the Microsoft Excel spreadsheet file
%  named FILE.  Returns the data as a table.
%
%  KINEMATICS_LOOPS7JOINTS6LINKS06_AUG20_20_57 = IMPORTFILE(FILE, SHEET)
%  reads from the specified worksheet.
%
%  KINEMATICS_LOOPS7JOINTS6LINKS06_AUG20_20_57 = IMPORTFILE(FILE, SHEET,
%  DATALINES) reads from the specified worksheet for the specified row
%  interval(s). Specify DATALINES as a positive scalar integer or a
%  N-by-2 array of positive scalar integers for dis-contiguous row
%  intervals.
%
%  Example:
%  kinematics_loops7Joints6Links06_Aug20_20_57 = importfile("C:\Users\adgut\Downloads\kinematics_loops7Joints6Links06-Aug 20_20_57.xlsx", "Sheet1", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 06-Aug-2026 20:29:26

%% Input handling

% If no sheet is specified, read from Sheet1
if nargin == 1 || isempty(sheetName)
    sheetName = "Sheet1";
end

% If row start and end points are not specified, define defaults
lastRowOfDataIdx = 0;
if nargin <= 2
    dataLines = [2, Inf];
    lastRowOfDataIdx = 1;
elseif dataLines(end,2) >= Inf
    lastRowOfDataIdx = size(dataLines, 1);
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 15);

% Specify sheet and range
opts.Sheet = sheetName;
if lastRowOfDataIdx == 1
    opts.DataRange = "A" + dataLines(1, 1);
else
    opts.DataRange = "A" + dataLines(1, 1) + ":O" + dataLines(1, 2);
end

% Specify column names and types
opts.VariableNames = ["Angle", "JointAXCm", "JointAYCm", "JointBXCm", "JointBYCm", "JointCXCm", "JointCYCm", "JointDXCm", "JointDYCm", "JointEXCm", "JointEYCm", "JointFXCm", "JointFYCm", "JointGXCm", "JointGYCm"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Import the data
kinematics_loops7Joints6Links06_Aug20_20_57 = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    if idx == lastRowOfDataIdx
        opts.DataRange = "A" + dataLines(idx, 1);
    else
        opts.DataRange = "A" + dataLines(idx, 1) + ":O" + dataLines(idx, 2);
    end
    tb = readtable(workbookFile, opts, "UseExcel", false);
    kinematics_loops7Joints6Links06_Aug20_20_57 = [kinematics_loops7Joints6Links06_Aug20_20_57; tb]; %#ok<AGROW>
end

end