%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\adgut\Downloads\kinematics_loops7Joints6Links06-Aug 20_20_57.xlsx
%    Worksheet: Sheet1
%
% Auto-generated by MATLAB on 06-Aug-2026 20:30:18

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 15);

% Specify sheet and range
opts.Sheet = "Sheet1";
opts.DataRange = "A2:O646";

% Specify column names and types
opts.VariableNames = ["Angle", "JointAXCm", "JointAYCm", "JointBXCm", "JointBYCm", "JointCXCm", "JointCYCm", "JointDXCm", "JointDYCm", "JointEXCm", "JointEYCm", "JointFXCm", "JointFYCm", "JointGXCm", "JointGYCm"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Import the data
kinematics_loops7Joints6Links06_Aug20_20_57 = readtable("C:\Users\adgut\Downloads\kinematics_loops7Joints6Links06-Aug 20_20_57.xlsx", opts, "UseExcel", false);


%% Clear temporary variables
clear opts